# Generated by Django 2.2.3 on 2019-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
